### ISSUE TITLE
Confusing error message when parsing date

### ISSUE THREAD

**Issue by MartinSStewart** [justinmimbs/elm-date-basic#22]
`Date.fromIsoString "1999-"` returns `Expected a date in ISO 8601 format; Expected a date in ISO 8601 format; Expected a date in ISO 8601 format` instead of just `Expected a date in ISO 8601 format`.

**Comment by justinmimbs** [comment]
Thanks for the report, Martin! This should be fixed now in [3.2.1](https://package.elm-lang.org/packages/justinmimbs/date/3.2.1/).

Justin

**Comment by MartinSStewart** [comment]
Great, thanks for the quick fix!

**Comment by MartinSStewart** [comment]
Oh, I noticed you changed the Elm version from `0.19.0` to `0.19.1`. Is that necessary? Otherwise I think it's best to leave it at `0.19.0` so that people using that version still have access to your package.

**Comment by justinmimbs** [comment]
Thanks, I only changed the Elm version on the application `elm.json` used for running tests. The package `elm.json` still allows `0.19.0`. 👍
